/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package rankteamsbyvote

import kotlin.test.Test
import kotlin.test.assertNotNull

class SolutionTest {
    @Test fun appHasAGreeting() {
        val classUnderTest = Solution()
        assertNotNull(classUnderTest.rankTeams(arrayOf("ABC","ACB","ABC","ACB","ACB")), "app should have a greeting")
    }
}
