/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package rankteamsbyvote

class Solution {
    fun rankTeams(votes: Array<String>): String {

        if (votes.isEmpty())
            return ""

        if (votes.size == 1)
            return votes[0]

        val votesRank = ArrayList<HashMap<String, Int>>(1000)
        votes.forEach {
            println(it)
            it.forEachIndexed { index, c: Char ->
                val teamKey = c.toString()
                val rank = votesRank[index]
                println(rank)
                val votes: Int = rank.getOrDefault(teamKey, 0) + 1
                println(rank)
                rank[teamKey] = votes
            }
            return "9"
        }
    }

    fun main() {
        val solution = Solution()
        println(solution.rankTeams(arrayOf("ABC", "ACB", "ABC", "ACB", "ACB")))
    }
