/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package snakegame

import kotlin.test.Test
import kotlin.test.assertEquals

class SnakeGameTest {
    @Test
    fun snakeMoves() {
        val classUnderTest = SnakeGame(3, 2, arrayOf(intArrayOf(1, 2), intArrayOf(0, 1)))
        val expected = "[0,0,1,1,2,-1]"
        var actual = "["
        actual += classUnderTest.move("R")
        actual += "," + classUnderTest.move("D")
        actual += "," + classUnderTest.move("R")
        actual += "," + classUnderTest.move("U")
        actual += "," + classUnderTest.move("L")
        actual += "," + classUnderTest.move("U")
        actual += "]"

        assertEquals(expected, actual)
    }

    @Test
    fun snakeMovesLeet1() {
        val classUnderTest = SnakeGame(2, 1, arrayOf(intArrayOf(0, 1)))
        val expected = "[1,-1]"
        var actual = "["
        actual += classUnderTest.move("R")
        actual += "," + classUnderTest.move("R")
        actual += "]"

        assertEquals(expected, actual)
    }

    @Test
    fun snakeMovesLeet2() {
        val classUnderTest = SnakeGame(
            3,
            3,
            arrayOf(
                intArrayOf(2, 0),
                intArrayOf(0, 0),
                intArrayOf(0, 2),
                intArrayOf(0, 1),
                intArrayOf(2, 2),
                intArrayOf(0, 1)
            )
        )
        val expected = "[0,1,1,1,1,2,2,2,2,3,4,4,4,4,-1]"
        var actual = "["
        actual += classUnderTest.move("D")
        actual += "," + classUnderTest.move("D")
        actual += "," + classUnderTest.move("R")
        actual += "," + classUnderTest.move("U")
        actual += "," + classUnderTest.move("U")
        actual += "," + classUnderTest.move("L")
        actual += "," + classUnderTest.move("D")
        actual += "," + classUnderTest.move("R")
        actual += "," + classUnderTest.move("R")
        actual += "," + classUnderTest.move("U")
        actual += "," + classUnderTest.move("L")
        actual += "," + classUnderTest.move("L")
        actual += "," + classUnderTest.move("D")
        actual += "," + classUnderTest.move("R")
        actual += "," + classUnderTest.move("U")
        actual += "]"

        assertEquals(expected, actual)
    }
}
